### ISSUE TITLE
background-size

### ISSUE THREAD

**Issue by kaukas** [agrobbin/spritely#20]
Hello.

Thank you for the nice helper to deal with sprites in Rails!

I am using "spritely" to compile sprite images for normal screens and now I need to do the same for the retina screens. For that I need to set the [`background-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size) property to half the dimensions of the whole compiled image [as demonistrated on tutsplus](http://code.tutsplus.com/tutorials/the-right-way-to-retinafy-your-websites--net-31793#highlighter_778097). Do you know how I could get the dimensions of the compiled image?

Thank you!

**Comment by agrobbin** [comment]
Hi @kaukas! Sorry for slow response. Right now there is no built-in support for getting the compiled sprite's total dimensions in the released version of spritely. However, if you try out #21 and it works for you, I'll merge it and release `v1.1.0`.

**Comment by kaukas** [comment]
I have to say I am impressed. The fix was quick and it works very well, at least in our situation. Thank you! Looking forward to the merge!

**Comment by agrobbin** [comment]
@kaukas thanks! `v1.1.0` has been released to RubyGems.
